export default function ReportLists({ report }: {
    report: any;
}) {
    const rootCauses = report.rootCauses || [];
    const predictive = report.predictive || [];
    return <><div className="split" style={{ marginTop: 16 }}><List title="Motor Bazlı" rows={report.byMotor}/><List title="Kategori Bazlı" rows={report.byCategory}/></div><div className="split" style={{ marginTop: 16 }}><List title="Aylık Arıza Trendi" rows={report.monthly}/><List title="Öncelik Dağılımı" rows={report.priority}/></div><div className="card" style={{ marginTop: 16, overflowX: 'auto' }}><h2>Teknisyen Bazlı</h2><table className="table"><thead><tr><th>Teknisyen</th><th>Arıza</th></tr></thead><tbody>{report.byTechnician.map((x: any) => <tr key={x.name}><td>{x.name}</td><td>{x.count}</td></tr>)}</tbody></table></div>{rootCauses.length > 0 && <div className="card" style={{ marginTop: 16 }}><h2>Tekrarlayan Kök Nedenler</h2><p className="muted">Teknik raporlarda kaydedilen kök neden metinlerinin sıklığı — tekrarlayan sorunları tespit etmek için.</p>{rootCauses.slice(0, 15).map((x: any) => <div className="row" style={{ justifyContent: 'space-between', padding: '8px 0', borderBottom: '1px solid var(--line)' }} key={x.name}><span>{x.name}</span><b>{x.count}</b></div>)}</div>}{predictive.length > 0 && <div className="card" style={{ marginTop: 16, overflowX: 'auto' }}><h2>Motor Risk / Öngörü Görünümü</h2><p className="muted">Son 90 gündeki arıza sıklığı ve gözlemlenen çalışma saati verisine göre tahmini risk sıralaması. Bakım planlaması için bir gösterge niteliğindedir, kesin bir tahmin değildir.</p><table className="table"><thead><tr><th>Motor</th><th>Toplam Arıza</th><th>Son 90 Gün</th><th>Ort. Saat / Arıza</th><th>Risk</th></tr></thead><tbody>{predictive.map((x: any) => <tr key={x.id}><td>{x.name}</td><td>{x.count}</td><td>{x.recent90Days}</td><td>{x.averageHoursPerBreakdown ?? '—'}</td><td><span className={`badge priority-${x.riskLabel === 'yüksek' ? 'kritik' : x.riskLabel === 'orta' ? 'orta' : 'dusuk'}`}>{x.riskLabel}</span></td></tr>)}</tbody></table></div>}</>;
}
function List({ title, rows }: {
    title: string;
    rows: any[];
}) { return <div className="card"><h2>{title}</h2>{rows.slice(0, 15).map((x: any) => <div className="row" style={{ justifyContent: 'space-between', padding: '8px 0', borderBottom: '1px solid var(--line)' }} key={x.name}><span>{x.name}</span><b>{x.count}</b></div>)}</div>; }

