import {NextResponse} from 'next/server';
import bcrypt from 'bcryptjs';
import {randomUUID} from 'crypto';
import {db} from '@/lib/db';
import {getCurrentUser} from '@/lib/auth';
import {z} from 'zod';
const roles=['yonetici','teknisyen','operator','goruntuleyici'] as const;
const schema=z.object({name:z.string().min(2).max(100),email:z.string().email(),password:z.string().min(8).max(128),role:z.enum(roles)});
export async function GET(){const u=await getCurrentUser();if(!u||u.role!=='yonetici')return NextResponse.json({error:'Yetkisiz'},{status:403});const rows=await (await db()).collection('users').find({}, {projection:{passwordHash:0}}).sort({name:1}).toArray();return NextResponse.json(rows)}
export async function POST(req:Request){const u=await getCurrentUser();if(!u||u.role!=='yonetici')return NextResponse.json({error:'Yetkisiz'},{status:403});const parsed=schema.safeParse(await req.json());if(!parsed.success)return NextResponse.json({error:'Geçersiz kullanıcı bilgileri'},{status:400});const v=parsed.data;const d=await db();const email=v.email.toLowerCase();if(await d.collection('users').findOne({email}))return NextResponse.json({error:'Bu e-posta zaten kayıtlı'},{status:409});const item={_id:randomUUID(),name:v.name.trim(),email,role:v.role,passwordHash:await bcrypt.hash(v.password,12),active:true,createdAt:new Date()};await d.collection('users').insertOne(item);return NextResponse.json({ok:true,user:{_id:item._id,name:item.name,email:item.email,role:item.role,active:true}},{status:201})}
export async function PATCH(req:Request){const u=await getCurrentUser();if(!u||u.role!=='yonetici')return NextResponse.json({error:'Yetkisiz'},{status:403});const body=await req.json();if(!body.id)return NextResponse.json({error:'Kullanıcı gerekli'},{status:400});const $set:any={updatedAt:new Date()};const targetId=String(body.id);if(targetId===String(u._id)&&body.role&&body.role!=='yonetici')return NextResponse.json({error:'Kendi yönetici rolünüzü değiştiremezsiniz'},{status:400});if(targetId===String(u._id)&&body.active===false)return NextResponse.json({error:'Kendi hesabınızı pasifleştiremezsiniz'},{status:400});if(typeof body.name==='string'&&body.name.trim())$set.name=body.name.trim();if(roles.includes(body.role))$set.role=body.role;if(typeof body.active==='boolean')$set.active=body.active;if(typeof body.password==='string'&&body.password.length>=8)$set.passwordHash=await bcrypt.hash(body.password,12);if(($set.active===false||$set.role&&$set.role!=='yonetici')){const target=await (await db()).collection('users').findOne({_id:targetId});if(target?.role==='yonetici'&&target.active){const others=await (await db()).collection('users').countDocuments({_id:{$ne:targetId},role:'yonetici',active:true});if(others===0)return NextResponse.json({error:'Sistemde en az bir aktif yönetici kalmalıdır'},{status:400});}}const r=await (await db()).collection('users').updateOne({_id:String(body.id)},{$set});if(!r.matchedCount)return NextResponse.json({error:'Kullanıcı bulunamadı'},{status:404});return NextResponse.json({ok:true})}
