import {getCurrentUser} from '@/lib/auth';
import {db} from '@/lib/db';
import Link from 'next/link';

const statusLabel:Record<string,string>={acik:'Açık',atandi:'Atandı',devam_ediyor:'Devam ediyor',onay_bekliyor:'Onay bekliyor',revizyon:'Revizyon',onaylandi:'Kapandı',iptal:'İptal'};
const fmt=(m:number|null)=>m===null?'—':`${Math.floor(m/60)}s ${m%60}dk`;

export default async function MotorDetail({params}:{params:Promise<{id:string}>}){
 const u=await getCurrentUser(); if(!u)return null;
 const {id}=await params; const d=await db(); const motor=await d.collection('motors').findOne({_id:id,active:true});
 if(!motor)return <><Link className="btn" href="/motorlar">← Motorlar</Link><div className="card" style={{marginTop:16}}>Motor bulunamadı.</div></>;
 const rows=await d.collection('breakdowns').find({motorId:id}).sort({createdAt:-1}).limit(500).toArray();
 const mttr=rows.map(x=>x.startedAt&&x.closedAt?Math.max(0,Math.round((new Date(x.closedAt).getTime()-new Date(x.startedAt).getTime())/60000)):null).filter((x):x is number=>x!==null);
 const categories=[...rows.reduce((m,x)=>{const k=String(x.categoryName||'Tanımsız');m.set(k,(m.get(k)||0)+1);return m},new Map<string,number>())].sort((a,b)=>b[1]-a[1]);
 return <><div className="row"><Link className="btn" href="/motorlar">← Motorlar</Link><Link className="btn" href={`/arizalar?motor=${encodeURIComponent(id)}`}>Arıza Kayıtları</Link></div><div className="dashboard-head" style={{marginTop:14}}><div><div className="eyebrow">AGM • MOTOR KARNESİ</div><h1 className="page-title">{motor.name}</h1><p className="muted">Kaynak: {motor.source==='agm-bakim-merkezi'?'Mevcut AGM sistemi':'Arızi Bakım Merkezi'} · Güncelleme: {motor.sourceUpdateDate||'—'}</p></div><span className="badge">{motor.active?'Aktif':'Pasif'}</span></div>
 <div className="grid cards dashboard-kpis"><div className="card kpi"><span>Çalışma Saati</span><strong>{Number(motor.currentHours||0).toLocaleString('tr-TR')} h</strong><small>Son aktarılan değer</small></div><div className="card kpi"><span>Yük</span><strong>{motor.currentLoad??'—'}</strong><small>Mevcut AGM verisi</small></div><div className="card kpi"><span>Toplam Arıza</span><strong>{rows.length}</strong><small>Bu motorun kayıtları</small></div><div className="card kpi"><span>Kritik</span><strong className={rows.some(x=>x.priority==='kritik'&&x.status!=='onaylandi')?'priority-critical':''}>{rows.filter(x=>x.priority==='kritik').length}</strong><small>Kritik kayıt</small></div><div className="card kpi"><span>Ortalama MTTR</span><strong>{fmt(mttr.length?Math.round(mttr.reduce((a,b)=>a+b,0)/mttr.length):null)}</strong><small>Başlangıç → kapanış</small></div></div>
 <div className="split" style={{marginTop:16}}><section className="card"><h2>Bakım Özeti</h2><div className="detail-grid"><div><b>Yağ</b><br/>{motor.oil?.brand||'—'}</div><div><b>Son yağ değişimi</b><br/>{motor.oil?.changeHour?.toLocaleString('tr-TR')||'—'} h</div><div><b>Yağ periyodu</b><br/>{motor.oil?.maxHours?`${motor.oil.maxHours.toLocaleString('tr-TR')} h`:'—'}</div><div><b>Veri tarihi</b><br/>{motor.sourceUpdateDate||'—'}</div></div><h3 style={{marginTop:20}}>Planlı bakım snapshot</h3><div className="table-wrap"><table className="table"><thead><tr><th>Bakım</th><th>Son Saat</th><th>Periyot</th><th>Sonraki Saat</th></tr></thead><tbody>{(motor.maintenanceSnapshot||[]).map((x:any)=><tr key={x.key}><td>{x.label}</td><td>{Number(x.lastHour||0).toLocaleString('tr-TR')}</td><td>{Number(x.period||0).toLocaleString('tr-TR')}</td><td>{Number(x.lastHour||0)+Number(x.period||0)>0?(Number(x.lastHour||0)+Number(x.period||0)).toLocaleString('tr-TR'):'—'}</td></tr>)}</tbody></table></div></section><section className="card"><h2>Arıza Dağılımı</h2>{categories.length?categories.slice(0,12).map(([name,count])=><div className="workload-row" key={name}><span>{name}</span><div><div className="workload-bar"><i style={{width:`${Math.min(100,count/Math.max(1,rows.length)*100)}%`}}/></div></div><b>{count}</b></div>):<p className="muted">Henüz arıza kaydı yok.</p>}</section></div>
 <section className="card" style={{marginTop:16}}><div className="row" style={{justifyContent:'space-between'}}><div><h2>Kronolojik Arıza Geçmişi</h2><p className="muted">Bu motora ait tüm arızi bakım kayıtları</p></div><span className="badge">{rows.length} kayıt</span></div><div className="table-wrap"><table className="table"><thead><tr><th>Kod</th><th>Tarih</th><th>Kategori</th><th>Öncelik</th><th>Teknisyen</th><th>Durum</th><th>MTTR</th></tr></thead><tbody>{rows.map((x:any)=>{const m=x.startedAt&&x.closedAt?Math.max(0,Math.round((new Date(x.closedAt).getTime()-new Date(x.startedAt).getTime())/60000)):null;return <tr key={String(x._id)}><td><Link href={`/arizalar/${x._id}`}><b>{x.code}</b></Link><small className="cell-sub">{x.title}</small></td><td>{new Date(x.createdAt).toLocaleString('tr-TR')}</td><td>{x.categoryName}{x.subcategoryName?` / ${x.subcategoryName}`:''}</td><td><span className={`badge priority-${x.priority}`}>{x.priority}</span></td><td>{x.assignedTechnicianName||'—'}</td><td>{statusLabel[x.status]||x.status}</td><td>{fmt(m)}</td></tr>})}</tbody></table></div></section>
 </>;
}
